### PR TITLE
Use NaN and make compatible with node v0.12.x

### PR DESCRIPTION
**Pull request by Prior99**
Use NaN instead of old deprecated API in order to make this compatible with node 0.12.x

### CODE REVIEW

**Comment by Rantanen** [comment]
Thanks!

**Comment by Prior99** [comment]
When trying to run node-mumbles "loopback" test I get some uint decode error. Might this be related to this PR?

**Comment by Prior99** [comment]
NVM was because of the server forcing Opus.

**Comment by Rantanen** [comment]
If this is causing problems, I wrapped opus 1.1 as a node library:
http://github.com/Rantanen/node-opus (opus on npm).

Didn't write the support for node-mumble yet though. Getting late so I'm too lazy to figure out what flags to set to tell Mumble we support Opus and more importantly how Mumble tells us the audio packets are now opus-encoded.

Also too tired to figure out how the encoder should be plugged into the existing packet handling, especially given opus encoder needs frame size per packet, not per encoder/decoder.

**Comment by Prior99** [comment]
Thank you. I guess I will have a look at it after I figured out how to get node-mumble to play anything from a stream as streaming PCM directly to it's inputstream seems to only create noise :D

**Comment by Rantanen** [comment]
Did the loopback test work? Make sure the PCM is 16-bit little endian.

(Also the real reason I'm still posting is to correct the npm name: node-opus as opus alone was taken with the most useless implementation ever \o/)

**Comment by Prior99** [comment]
Yeah, the loopback is working. Using the output from the test of node.celt doesn't work, it only produces noise. 

```javascript
    var rs = fs.createReadStream("out.pcm");
    rs.once('readable', function() {
          rs.pipe(connection.inputStream());
    });
```

**Comment by Rantanen** [comment]
My bad! The file streams used chunks larger than my tests and I had made a stupid mistake with these. It should work now.

**Comment by Prior99** [comment]
Very nice. Thank you!

**Pull request merged**
